name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_3YhpC5zAG6ABNBBrwBoUss7O
      VERCEL_PROJECT_ID: prj_Xn5WfGpvHlklew9s75c4xiPtOLQf
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token="${{ secrets.VERCEL_TOKEN }}" --yes
